### ISSUE TITLE
A new drag and drop option that doesn't yet exist in the tool

### ISSUE THREAD

**Issue by JuninhoLeo** [benfoley/ionic-dragula#1]
Hello, how are you? I'm here to ask you to evaluate putting this drag and drop option for this tool to be complete. From my studies at Dragula, a need arose that when I drag he can copy or move the object, but he does not have the option of replacing, for example, when I drag one object on top of another, he does not have the option of erase the bottom and replace with what is being dragged. Thanks in advance, I hope you can develop this functionality for dragula.

Att. José Leocadio de Barros Junior

**Comment by benfoley** [comment]
Hi, it would be best to ask in the Dragula repository at https://github.com/bevacqua/dragula
